server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/saga_cashback
    username: adm
    password: adm
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jpa:
    hibernate:
      ddl-auto: create

cashback:
  rate: 10
  hundred: 100
